version: '3.9'

services:
  api-service:
    container_name: api-container
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8000'
    networks:
      - backend

#  api-service1:
#    container_name: api-container2
#    image: thaohn-api
#    ports:
#      - '8001:8000'
#    networks:
#      - backend


networks:
  backend:
    driver: bridge