
server:
  port: 8000
spring:
  application:
    name: thaohn-java-app
  config:
    activate:
      on-profile: dev

openapi:
  service:
    api-docs : api-service
    server: http://localhost:${server.port}
    title: ${API_TITLE:DUMMY-API-TITLE}
    version : 1.0

